export { BrevoEmailAdapter } from "./brevo.adapter"
export { getEmailAdapter, sendEmail } from "./email.service"
export { NoopEmailAdapter } from "./noop.adapter"
export { ResendEmailAdapter } from "./resend.adapter"
export type { EmailAdapter, SendEmailParams, SendEmailResult } from "./types"
