/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as UploadsSplatRouteImport } from './routes/uploads/$'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as AdminRifasRouteImport } from './routes/admin/rifas'
import { Route as AdminMetodosPagoRouteImport } from './routes/admin/metodos-pago'
import { Route as AdminEmailsRouteImport } from './routes/admin/emails'
import { Route as AdminCuentaRouteImport } from './routes/admin/cuenta'
import { Route as AdminCrearRouteImport } from './routes/admin/crear'
import { Route as AdminConfigRouteImport } from './routes/admin/config'
import { Route as AdminComprasRouteImport } from './routes/admin/compras'
import { Route as AdminBoletosRouteImport } from './routes/admin/boletos'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as PublicVerificarRouteImport } from './routes/_public/verificar'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as ApiRafflesIndexRouteImport } from './routes/api/raffles/index'
import { Route as ApiPurchasesIndexRouteImport } from './routes/api/purchases/index'
import { Route as AdminRifasIndexRouteImport } from './routes/admin/rifas/index'
import { Route as ApiTicketsVerifyRouteImport } from './routes/api/tickets.verify'
import { Route as ApiRafflesFirstActiveRouteImport } from './routes/api/raffles/first-active'
import { Route as ApiRafflesIdRouteImport } from './routes/api/raffles/$id'
import { Route as ApiPurchasesTopClientsRouteImport } from './routes/api/purchases.top-clients'
import { Route as ApiPurchaseSuccessAnalyticsRouteImport } from './routes/api/purchase-success/analytics'
import { Route as ApiHealthDbRouteImport } from './routes/api/health/db'
import { Route as ApiCronMaintenanceRouteImport } from './routes/api/cron/maintenance'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminUploadRouteImport } from './routes/api/admin/upload'
import { Route as ApiAdminMaintenanceRouteImport } from './routes/api/admin/maintenance'
import { Route as ApiAdminEmailsRouteImport } from './routes/api/admin/emails'
import { Route as ApiAdminDashboardRouteImport } from './routes/api/admin/dashboard'
import { Route as ApiAdminConfigRouteImport } from './routes/api/admin/config'
import { Route as ApiAdminAnalyticsRouteImport } from './routes/api/admin/analytics'
import { Route as AdminRifasIdRouteImport } from './routes/admin/rifas/$id'
import { Route as AdminEditIdRouteImport } from './routes/admin/edit/$id'
import { Route as PublicRifaIdRouteImport } from './routes/_public/rifa/$id'
import { Route as ApiAdminRafflesIndexRouteImport } from './routes/api/admin/raffles/index'
import { Route as ApiAdminPurchasesIndexRouteImport } from './routes/api/admin/purchases/index'
import { Route as ApiAdminPaymentAccountsIndexRouteImport } from './routes/api/admin/payment-accounts/index'
import { Route as ApiRafflesIdPauseInfoRouteImport } from './routes/api/raffles/$id.pause-info'
import { Route as ApiAdminRafflesIdRouteImport } from './routes/api/admin/raffles/$id'
import { Route as ApiAdminPurchasesIdRouteImport } from './routes/api/admin/purchases/$id'
import { Route as ApiAdminPaymentAccountsIdRouteImport } from './routes/api/admin/payment-accounts/$id'
import { Route as ApiAdminMePreferencesRouteImport } from './routes/api/admin/me/preferences'
import { Route as ApiAdminEmailsStatsRouteImport } from './routes/api/admin/emails.stats'
import { Route as ApiAdminEmailsHealthRouteImport } from './routes/api/admin/emails.health'
import { Route as ApiAdminEmailsLogIdRouteImport } from './routes/api/admin/emails.$logId'
import { Route as ApiAdminAnalyticsSummaryRouteImport } from './routes/api/admin/analytics.summary'
import { Route as ApiAdminRafflesIdUnpauseRouteImport } from './routes/api/admin/raffles/$id.unpause'
import { Route as ApiAdminRafflesIdStatusRouteImport } from './routes/api/admin/raffles/$id.status'
import { Route as ApiAdminRafflesIdPublishRouteImport } from './routes/api/admin/raffles/$id.publish'
import { Route as ApiAdminRafflesIdPromotionsRouteImport } from './routes/api/admin/raffles/$id.promotions'
import { Route as ApiAdminRafflesIdPauseRouteImport } from './routes/api/admin/raffles/$id.pause'
import { Route as ApiAdminRafflesIdLifecycleRouteImport } from './routes/api/admin/raffles/$id.lifecycle'
import { Route as ApiAdminRafflesIdAutoPauseRouteImport } from './routes/api/admin/raffles/$id.auto-pause'
import { Route as ApiAdminPurchasesIdStatusRouteImport } from './routes/api/admin/purchases/$id.status'
import { Route as ApiAdminPurchasesIdEmailsRouteImport } from './routes/api/admin/purchases.$id.emails'
import { Route as ApiAdminPurchasesIdCustomerRouteImport } from './routes/api/admin/purchases/$id.customer'
import { Route as ApiAdminPaymentAccountsIdUsageRouteImport } from './routes/api/admin/payment-accounts/$id.usage'
import { Route as ApiAdminEmailsLogIdResendRouteImport } from './routes/api/admin/emails.$logId.resend'
import { Route as ApiAdminRafflesIdPromotionsPromotionIdRouteImport } from './routes/api/admin/raffles/$id.promotions.$promotionId'
import { Route as ApiAdminPurchasesIdTicketsRemoveRouteImport } from './routes/api/admin/purchases/$id.tickets.remove'
import { Route as ApiAdminPurchasesIdTicketsReassignRouteImport } from './routes/api/admin/purchases/$id.tickets.reassign'
import { Route as ApiAdminPurchasesIdTicketsAddRouteImport } from './routes/api/admin/purchases/$id.tickets.add'
import { Route as ApiAdminPurchasesIdEmailsSendRouteImport } from './routes/api/admin/purchases.$id.emails.send'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const UploadsSplatRoute = UploadsSplatRouteImport.update({
  id: '/uploads/$',
  path: '/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRifasRoute = AdminRifasRouteImport.update({
  id: '/rifas',
  path: '/rifas',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMetodosPagoRoute = AdminMetodosPagoRouteImport.update({
  id: '/metodos-pago',
  path: '/metodos-pago',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCuentaRoute = AdminCuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCrearRoute = AdminCrearRouteImport.update({
  id: '/crear',
  path: '/crear',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminComprasRoute = AdminComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBoletosRoute = AdminBoletosRouteImport.update({
  id: '/boletos',
  path: '/boletos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicVerificarRoute = PublicVerificarRouteImport.update({
  id: '/verificar',
  path: '/verificar',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ApiRafflesIndexRoute = ApiRafflesIndexRouteImport.update({
  id: '/api/raffles/',
  path: '/api/raffles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPurchasesIndexRoute = ApiPurchasesIndexRouteImport.update({
  id: '/api/purchases/',
  path: '/api/purchases/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRifasIndexRoute = AdminRifasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRifasRoute,
} as any)
const ApiTicketsVerifyRoute = ApiTicketsVerifyRouteImport.update({
  id: '/api/tickets/verify',
  path: '/api/tickets/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRafflesFirstActiveRoute = ApiRafflesFirstActiveRouteImport.update({
  id: '/api/raffles/first-active',
  path: '/api/raffles/first-active',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRafflesIdRoute = ApiRafflesIdRouteImport.update({
  id: '/api/raffles/$id',
  path: '/api/raffles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPurchasesTopClientsRoute = ApiPurchasesTopClientsRouteImport.update({
  id: '/api/purchases/top-clients',
  path: '/api/purchases/top-clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPurchaseSuccessAnalyticsRoute =
  ApiPurchaseSuccessAnalyticsRouteImport.update({
    id: '/api/purchase-success/analytics',
    path: '/api/purchase-success/analytics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiHealthDbRoute = ApiHealthDbRouteImport.update({
  id: '/api/health/db',
  path: '/api/health/db',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronMaintenanceRoute = ApiCronMaintenanceRouteImport.update({
  id: '/api/cron/maintenance',
  path: '/api/cron/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadRoute = ApiAdminUploadRouteImport.update({
  id: '/api/admin/upload',
  path: '/api/admin/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMaintenanceRoute = ApiAdminMaintenanceRouteImport.update({
  id: '/api/admin/maintenance',
  path: '/api/admin/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminEmailsRoute = ApiAdminEmailsRouteImport.update({
  id: '/api/admin/emails',
  path: '/api/admin/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDashboardRoute = ApiAdminDashboardRouteImport.update({
  id: '/api/admin/dashboard',
  path: '/api/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminConfigRoute = ApiAdminConfigRouteImport.update({
  id: '/api/admin/config',
  path: '/api/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAnalyticsRoute = ApiAdminAnalyticsRouteImport.update({
  id: '/api/admin/analytics',
  path: '/api/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRifasIdRoute = AdminRifasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminRifasRoute,
} as any)
const AdminEditIdRoute = AdminEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicRifaIdRoute = PublicRifaIdRouteImport.update({
  id: '/rifa/$id',
  path: '/rifa/$id',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ApiAdminRafflesIndexRoute = ApiAdminRafflesIndexRouteImport.update({
  id: '/api/admin/raffles/',
  path: '/api/admin/raffles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPurchasesIndexRoute = ApiAdminPurchasesIndexRouteImport.update({
  id: '/api/admin/purchases/',
  path: '/api/admin/purchases/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPaymentAccountsIndexRoute =
  ApiAdminPaymentAccountsIndexRouteImport.update({
    id: '/api/admin/payment-accounts/',
    path: '/api/admin/payment-accounts/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRafflesIdPauseInfoRoute = ApiRafflesIdPauseInfoRouteImport.update({
  id: '/pause-info',
  path: '/pause-info',
  getParentRoute: () => ApiRafflesIdRoute,
} as any)
const ApiAdminRafflesIdRoute = ApiAdminRafflesIdRouteImport.update({
  id: '/api/admin/raffles/$id',
  path: '/api/admin/raffles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPurchasesIdRoute = ApiAdminPurchasesIdRouteImport.update({
  id: '/api/admin/purchases/$id',
  path: '/api/admin/purchases/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPaymentAccountsIdRoute =
  ApiAdminPaymentAccountsIdRouteImport.update({
    id: '/api/admin/payment-accounts/$id',
    path: '/api/admin/payment-accounts/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminMePreferencesRoute = ApiAdminMePreferencesRouteImport.update({
  id: '/api/admin/me/preferences',
  path: '/api/admin/me/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminEmailsStatsRoute = ApiAdminEmailsStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => ApiAdminEmailsRoute,
} as any)
const ApiAdminEmailsHealthRoute = ApiAdminEmailsHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => ApiAdminEmailsRoute,
} as any)
const ApiAdminEmailsLogIdRoute = ApiAdminEmailsLogIdRouteImport.update({
  id: '/$logId',
  path: '/$logId',
  getParentRoute: () => ApiAdminEmailsRoute,
} as any)
const ApiAdminAnalyticsSummaryRoute =
  ApiAdminAnalyticsSummaryRouteImport.update({
    id: '/summary',
    path: '/summary',
    getParentRoute: () => ApiAdminAnalyticsRoute,
  } as any)
const ApiAdminRafflesIdUnpauseRoute =
  ApiAdminRafflesIdUnpauseRouteImport.update({
    id: '/unpause',
    path: '/unpause',
    getParentRoute: () => ApiAdminRafflesIdRoute,
  } as any)
const ApiAdminRafflesIdStatusRoute = ApiAdminRafflesIdStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiAdminRafflesIdRoute,
} as any)
const ApiAdminRafflesIdPublishRoute =
  ApiAdminRafflesIdPublishRouteImport.update({
    id: '/publish',
    path: '/publish',
    getParentRoute: () => ApiAdminRafflesIdRoute,
  } as any)
const ApiAdminRafflesIdPromotionsRoute =
  ApiAdminRafflesIdPromotionsRouteImport.update({
    id: '/promotions',
    path: '/promotions',
    getParentRoute: () => ApiAdminRafflesIdRoute,
  } as any)
const ApiAdminRafflesIdPauseRoute = ApiAdminRafflesIdPauseRouteImport.update({
  id: '/pause',
  path: '/pause',
  getParentRoute: () => ApiAdminRafflesIdRoute,
} as any)
const ApiAdminRafflesIdLifecycleRoute =
  ApiAdminRafflesIdLifecycleRouteImport.update({
    id: '/lifecycle',
    path: '/lifecycle',
    getParentRoute: () => ApiAdminRafflesIdRoute,
  } as any)
const ApiAdminRafflesIdAutoPauseRoute =
  ApiAdminRafflesIdAutoPauseRouteImport.update({
    id: '/auto-pause',
    path: '/auto-pause',
    getParentRoute: () => ApiAdminRafflesIdRoute,
  } as any)
const ApiAdminPurchasesIdStatusRoute =
  ApiAdminPurchasesIdStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => ApiAdminPurchasesIdRoute,
  } as any)
const ApiAdminPurchasesIdEmailsRoute =
  ApiAdminPurchasesIdEmailsRouteImport.update({
    id: '/emails',
    path: '/emails',
    getParentRoute: () => ApiAdminPurchasesIdRoute,
  } as any)
const ApiAdminPurchasesIdCustomerRoute =
  ApiAdminPurchasesIdCustomerRouteImport.update({
    id: '/customer',
    path: '/customer',
    getParentRoute: () => ApiAdminPurchasesIdRoute,
  } as any)
const ApiAdminPaymentAccountsIdUsageRoute =
  ApiAdminPaymentAccountsIdUsageRouteImport.update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () => ApiAdminPaymentAccountsIdRoute,
  } as any)
const ApiAdminEmailsLogIdResendRoute =
  ApiAdminEmailsLogIdResendRouteImport.update({
    id: '/resend',
    path: '/resend',
    getParentRoute: () => ApiAdminEmailsLogIdRoute,
  } as any)
const ApiAdminRafflesIdPromotionsPromotionIdRoute =
  ApiAdminRafflesIdPromotionsPromotionIdRouteImport.update({
    id: '/$promotionId',
    path: '/$promotionId',
    getParentRoute: () => ApiAdminRafflesIdPromotionsRoute,
  } as any)
const ApiAdminPurchasesIdTicketsRemoveRoute =
  ApiAdminPurchasesIdTicketsRemoveRouteImport.update({
    id: '/tickets/remove',
    path: '/tickets/remove',
    getParentRoute: () => ApiAdminPurchasesIdRoute,
  } as any)
const ApiAdminPurchasesIdTicketsReassignRoute =
  ApiAdminPurchasesIdTicketsReassignRouteImport.update({
    id: '/tickets/reassign',
    path: '/tickets/reassign',
    getParentRoute: () => ApiAdminPurchasesIdRoute,
  } as any)
const ApiAdminPurchasesIdTicketsAddRoute =
  ApiAdminPurchasesIdTicketsAddRouteImport.update({
    id: '/tickets/add',
    path: '/tickets/add',
    getParentRoute: () => ApiAdminPurchasesIdRoute,
  } as any)
const ApiAdminPurchasesIdEmailsSendRoute =
  ApiAdminPurchasesIdEmailsSendRouteImport.update({
    id: '/send',
    path: '/send',
    getParentRoute: () => ApiAdminPurchasesIdEmailsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/verificar': typeof PublicVerificarRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/boletos': typeof AdminBoletosRoute
  '/admin/compras': typeof AdminComprasRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/crear': typeof AdminCrearRoute
  '/admin/cuenta': typeof AdminCuentaRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/metodos-pago': typeof AdminMetodosPagoRoute
  '/admin/rifas': typeof AdminRifasRouteWithChildren
  '/api/config': typeof ApiConfigRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/rifa/$id': typeof PublicRifaIdRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
  '/admin/rifas/$id': typeof AdminRifasIdRoute
  '/api/admin/analytics': typeof ApiAdminAnalyticsRouteWithChildren
  '/api/admin/config': typeof ApiAdminConfigRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/emails': typeof ApiAdminEmailsRouteWithChildren
  '/api/admin/maintenance': typeof ApiAdminMaintenanceRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/maintenance': typeof ApiCronMaintenanceRoute
  '/api/health/db': typeof ApiHealthDbRoute
  '/api/purchase-success/analytics': typeof ApiPurchaseSuccessAnalyticsRoute
  '/api/purchases/top-clients': typeof ApiPurchasesTopClientsRoute
  '/api/raffles/$id': typeof ApiRafflesIdRouteWithChildren
  '/api/raffles/first-active': typeof ApiRafflesFirstActiveRoute
  '/api/tickets/verify': typeof ApiTicketsVerifyRoute
  '/admin/rifas/': typeof AdminRifasIndexRoute
  '/api/purchases/': typeof ApiPurchasesIndexRoute
  '/api/raffles/': typeof ApiRafflesIndexRoute
  '/api/admin/analytics/summary': typeof ApiAdminAnalyticsSummaryRoute
  '/api/admin/emails/$logId': typeof ApiAdminEmailsLogIdRouteWithChildren
  '/api/admin/emails/health': typeof ApiAdminEmailsHealthRoute
  '/api/admin/emails/stats': typeof ApiAdminEmailsStatsRoute
  '/api/admin/me/preferences': typeof ApiAdminMePreferencesRoute
  '/api/admin/payment-accounts/$id': typeof ApiAdminPaymentAccountsIdRouteWithChildren
  '/api/admin/purchases/$id': typeof ApiAdminPurchasesIdRouteWithChildren
  '/api/admin/raffles/$id': typeof ApiAdminRafflesIdRouteWithChildren
  '/api/raffles/$id/pause-info': typeof ApiRafflesIdPauseInfoRoute
  '/api/admin/payment-accounts/': typeof ApiAdminPaymentAccountsIndexRoute
  '/api/admin/purchases/': typeof ApiAdminPurchasesIndexRoute
  '/api/admin/raffles/': typeof ApiAdminRafflesIndexRoute
  '/api/admin/emails/$logId/resend': typeof ApiAdminEmailsLogIdResendRoute
  '/api/admin/payment-accounts/$id/usage': typeof ApiAdminPaymentAccountsIdUsageRoute
  '/api/admin/purchases/$id/customer': typeof ApiAdminPurchasesIdCustomerRoute
  '/api/admin/purchases/$id/emails': typeof ApiAdminPurchasesIdEmailsRouteWithChildren
  '/api/admin/purchases/$id/status': typeof ApiAdminPurchasesIdStatusRoute
  '/api/admin/raffles/$id/auto-pause': typeof ApiAdminRafflesIdAutoPauseRoute
  '/api/admin/raffles/$id/lifecycle': typeof ApiAdminRafflesIdLifecycleRoute
  '/api/admin/raffles/$id/pause': typeof ApiAdminRafflesIdPauseRoute
  '/api/admin/raffles/$id/promotions': typeof ApiAdminRafflesIdPromotionsRouteWithChildren
  '/api/admin/raffles/$id/publish': typeof ApiAdminRafflesIdPublishRoute
  '/api/admin/raffles/$id/status': typeof ApiAdminRafflesIdStatusRoute
  '/api/admin/raffles/$id/unpause': typeof ApiAdminRafflesIdUnpauseRoute
  '/api/admin/purchases/$id/emails/send': typeof ApiAdminPurchasesIdEmailsSendRoute
  '/api/admin/purchases/$id/tickets/add': typeof ApiAdminPurchasesIdTicketsAddRoute
  '/api/admin/purchases/$id/tickets/reassign': typeof ApiAdminPurchasesIdTicketsReassignRoute
  '/api/admin/purchases/$id/tickets/remove': typeof ApiAdminPurchasesIdTicketsRemoveRoute
  '/api/admin/raffles/$id/promotions/$promotionId': typeof ApiAdminRafflesIdPromotionsPromotionIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof PublicLoginRoute
  '/verificar': typeof PublicVerificarRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/boletos': typeof AdminBoletosRoute
  '/admin/compras': typeof AdminComprasRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/crear': typeof AdminCrearRoute
  '/admin/cuenta': typeof AdminCuentaRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/metodos-pago': typeof AdminMetodosPagoRoute
  '/api/config': typeof ApiConfigRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/rifa/$id': typeof PublicRifaIdRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
  '/admin/rifas/$id': typeof AdminRifasIdRoute
  '/api/admin/analytics': typeof ApiAdminAnalyticsRouteWithChildren
  '/api/admin/config': typeof ApiAdminConfigRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/emails': typeof ApiAdminEmailsRouteWithChildren
  '/api/admin/maintenance': typeof ApiAdminMaintenanceRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/maintenance': typeof ApiCronMaintenanceRoute
  '/api/health/db': typeof ApiHealthDbRoute
  '/api/purchase-success/analytics': typeof ApiPurchaseSuccessAnalyticsRoute
  '/api/purchases/top-clients': typeof ApiPurchasesTopClientsRoute
  '/api/raffles/$id': typeof ApiRafflesIdRouteWithChildren
  '/api/raffles/first-active': typeof ApiRafflesFirstActiveRoute
  '/api/tickets/verify': typeof ApiTicketsVerifyRoute
  '/admin/rifas': typeof AdminRifasIndexRoute
  '/api/purchases': typeof ApiPurchasesIndexRoute
  '/api/raffles': typeof ApiRafflesIndexRoute
  '/api/admin/analytics/summary': typeof ApiAdminAnalyticsSummaryRoute
  '/api/admin/emails/$logId': typeof ApiAdminEmailsLogIdRouteWithChildren
  '/api/admin/emails/health': typeof ApiAdminEmailsHealthRoute
  '/api/admin/emails/stats': typeof ApiAdminEmailsStatsRoute
  '/api/admin/me/preferences': typeof ApiAdminMePreferencesRoute
  '/api/admin/payment-accounts/$id': typeof ApiAdminPaymentAccountsIdRouteWithChildren
  '/api/admin/purchases/$id': typeof ApiAdminPurchasesIdRouteWithChildren
  '/api/admin/raffles/$id': typeof ApiAdminRafflesIdRouteWithChildren
  '/api/raffles/$id/pause-info': typeof ApiRafflesIdPauseInfoRoute
  '/api/admin/payment-accounts': typeof ApiAdminPaymentAccountsIndexRoute
  '/api/admin/purchases': typeof ApiAdminPurchasesIndexRoute
  '/api/admin/raffles': typeof ApiAdminRafflesIndexRoute
  '/api/admin/emails/$logId/resend': typeof ApiAdminEmailsLogIdResendRoute
  '/api/admin/payment-accounts/$id/usage': typeof ApiAdminPaymentAccountsIdUsageRoute
  '/api/admin/purchases/$id/customer': typeof ApiAdminPurchasesIdCustomerRoute
  '/api/admin/purchases/$id/emails': typeof ApiAdminPurchasesIdEmailsRouteWithChildren
  '/api/admin/purchases/$id/status': typeof ApiAdminPurchasesIdStatusRoute
  '/api/admin/raffles/$id/auto-pause': typeof ApiAdminRafflesIdAutoPauseRoute
  '/api/admin/raffles/$id/lifecycle': typeof ApiAdminRafflesIdLifecycleRoute
  '/api/admin/raffles/$id/pause': typeof ApiAdminRafflesIdPauseRoute
  '/api/admin/raffles/$id/promotions': typeof ApiAdminRafflesIdPromotionsRouteWithChildren
  '/api/admin/raffles/$id/publish': typeof ApiAdminRafflesIdPublishRoute
  '/api/admin/raffles/$id/status': typeof ApiAdminRafflesIdStatusRoute
  '/api/admin/raffles/$id/unpause': typeof ApiAdminRafflesIdUnpauseRoute
  '/api/admin/purchases/$id/emails/send': typeof ApiAdminPurchasesIdEmailsSendRoute
  '/api/admin/purchases/$id/tickets/add': typeof ApiAdminPurchasesIdTicketsAddRoute
  '/api/admin/purchases/$id/tickets/reassign': typeof ApiAdminPurchasesIdTicketsReassignRoute
  '/api/admin/purchases/$id/tickets/remove': typeof ApiAdminPurchasesIdTicketsRemoveRoute
  '/api/admin/raffles/$id/promotions/$promotionId': typeof ApiAdminRafflesIdPromotionsPromotionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_public/verificar': typeof PublicVerificarRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/boletos': typeof AdminBoletosRoute
  '/admin/compras': typeof AdminComprasRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/crear': typeof AdminCrearRoute
  '/admin/cuenta': typeof AdminCuentaRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/metodos-pago': typeof AdminMetodosPagoRoute
  '/admin/rifas': typeof AdminRifasRouteWithChildren
  '/api/config': typeof ApiConfigRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_public/rifa/$id': typeof PublicRifaIdRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
  '/admin/rifas/$id': typeof AdminRifasIdRoute
  '/api/admin/analytics': typeof ApiAdminAnalyticsRouteWithChildren
  '/api/admin/config': typeof ApiAdminConfigRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/admin/emails': typeof ApiAdminEmailsRouteWithChildren
  '/api/admin/maintenance': typeof ApiAdminMaintenanceRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/maintenance': typeof ApiCronMaintenanceRoute
  '/api/health/db': typeof ApiHealthDbRoute
  '/api/purchase-success/analytics': typeof ApiPurchaseSuccessAnalyticsRoute
  '/api/purchases/top-clients': typeof ApiPurchasesTopClientsRoute
  '/api/raffles/$id': typeof ApiRafflesIdRouteWithChildren
  '/api/raffles/first-active': typeof ApiRafflesFirstActiveRoute
  '/api/tickets/verify': typeof ApiTicketsVerifyRoute
  '/admin/rifas/': typeof AdminRifasIndexRoute
  '/api/purchases/': typeof ApiPurchasesIndexRoute
  '/api/raffles/': typeof ApiRafflesIndexRoute
  '/api/admin/analytics/summary': typeof ApiAdminAnalyticsSummaryRoute
  '/api/admin/emails/$logId': typeof ApiAdminEmailsLogIdRouteWithChildren
  '/api/admin/emails/health': typeof ApiAdminEmailsHealthRoute
  '/api/admin/emails/stats': typeof ApiAdminEmailsStatsRoute
  '/api/admin/me/preferences': typeof ApiAdminMePreferencesRoute
  '/api/admin/payment-accounts/$id': typeof ApiAdminPaymentAccountsIdRouteWithChildren
  '/api/admin/purchases/$id': typeof ApiAdminPurchasesIdRouteWithChildren
  '/api/admin/raffles/$id': typeof ApiAdminRafflesIdRouteWithChildren
  '/api/raffles/$id/pause-info': typeof ApiRafflesIdPauseInfoRoute
  '/api/admin/payment-accounts/': typeof ApiAdminPaymentAccountsIndexRoute
  '/api/admin/purchases/': typeof ApiAdminPurchasesIndexRoute
  '/api/admin/raffles/': typeof ApiAdminRafflesIndexRoute
  '/api/admin/emails/$logId/resend': typeof ApiAdminEmailsLogIdResendRoute
  '/api/admin/payment-accounts/$id/usage': typeof ApiAdminPaymentAccountsIdUsageRoute
  '/api/admin/purchases/$id/customer': typeof ApiAdminPurchasesIdCustomerRoute
  '/api/admin/purchases/$id/emails': typeof ApiAdminPurchasesIdEmailsRouteWithChildren
  '/api/admin/purchases/$id/status': typeof ApiAdminPurchasesIdStatusRoute
  '/api/admin/raffles/$id/auto-pause': typeof ApiAdminRafflesIdAutoPauseRoute
  '/api/admin/raffles/$id/lifecycle': typeof ApiAdminRafflesIdLifecycleRoute
  '/api/admin/raffles/$id/pause': typeof ApiAdminRafflesIdPauseRoute
  '/api/admin/raffles/$id/promotions': typeof ApiAdminRafflesIdPromotionsRouteWithChildren
  '/api/admin/raffles/$id/publish': typeof ApiAdminRafflesIdPublishRoute
  '/api/admin/raffles/$id/status': typeof ApiAdminRafflesIdStatusRoute
  '/api/admin/raffles/$id/unpause': typeof ApiAdminRafflesIdUnpauseRoute
  '/api/admin/purchases/$id/emails/send': typeof ApiAdminPurchasesIdEmailsSendRoute
  '/api/admin/purchases/$id/tickets/add': typeof ApiAdminPurchasesIdTicketsAddRoute
  '/api/admin/purchases/$id/tickets/reassign': typeof ApiAdminPurchasesIdTicketsReassignRoute
  '/api/admin/purchases/$id/tickets/remove': typeof ApiAdminPurchasesIdTicketsRemoveRoute
  '/api/admin/raffles/$id/promotions/$promotionId': typeof ApiAdminRafflesIdPromotionsPromotionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/verificar'
    | '/admin/analytics'
    | '/admin/boletos'
    | '/admin/compras'
    | '/admin/config'
    | '/admin/crear'
    | '/admin/cuenta'
    | '/admin/emails'
    | '/admin/metodos-pago'
    | '/admin/rifas'
    | '/api/config'
    | '/uploads/$'
    | '/admin/'
    | '/rifa/$id'
    | '/admin/edit/$id'
    | '/admin/rifas/$id'
    | '/api/admin/analytics'
    | '/api/admin/config'
    | '/api/admin/dashboard'
    | '/api/admin/emails'
    | '/api/admin/maintenance'
    | '/api/admin/upload'
    | '/api/auth/$'
    | '/api/cron/maintenance'
    | '/api/health/db'
    | '/api/purchase-success/analytics'
    | '/api/purchases/top-clients'
    | '/api/raffles/$id'
    | '/api/raffles/first-active'
    | '/api/tickets/verify'
    | '/admin/rifas/'
    | '/api/purchases/'
    | '/api/raffles/'
    | '/api/admin/analytics/summary'
    | '/api/admin/emails/$logId'
    | '/api/admin/emails/health'
    | '/api/admin/emails/stats'
    | '/api/admin/me/preferences'
    | '/api/admin/payment-accounts/$id'
    | '/api/admin/purchases/$id'
    | '/api/admin/raffles/$id'
    | '/api/raffles/$id/pause-info'
    | '/api/admin/payment-accounts/'
    | '/api/admin/purchases/'
    | '/api/admin/raffles/'
    | '/api/admin/emails/$logId/resend'
    | '/api/admin/payment-accounts/$id/usage'
    | '/api/admin/purchases/$id/customer'
    | '/api/admin/purchases/$id/emails'
    | '/api/admin/purchases/$id/status'
    | '/api/admin/raffles/$id/auto-pause'
    | '/api/admin/raffles/$id/lifecycle'
    | '/api/admin/raffles/$id/pause'
    | '/api/admin/raffles/$id/promotions'
    | '/api/admin/raffles/$id/publish'
    | '/api/admin/raffles/$id/status'
    | '/api/admin/raffles/$id/unpause'
    | '/api/admin/purchases/$id/emails/send'
    | '/api/admin/purchases/$id/tickets/add'
    | '/api/admin/purchases/$id/tickets/reassign'
    | '/api/admin/purchases/$id/tickets/remove'
    | '/api/admin/raffles/$id/promotions/$promotionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/verificar'
    | '/admin/analytics'
    | '/admin/boletos'
    | '/admin/compras'
    | '/admin/config'
    | '/admin/crear'
    | '/admin/cuenta'
    | '/admin/emails'
    | '/admin/metodos-pago'
    | '/api/config'
    | '/uploads/$'
    | '/'
    | '/admin'
    | '/rifa/$id'
    | '/admin/edit/$id'
    | '/admin/rifas/$id'
    | '/api/admin/analytics'
    | '/api/admin/config'
    | '/api/admin/dashboard'
    | '/api/admin/emails'
    | '/api/admin/maintenance'
    | '/api/admin/upload'
    | '/api/auth/$'
    | '/api/cron/maintenance'
    | '/api/health/db'
    | '/api/purchase-success/analytics'
    | '/api/purchases/top-clients'
    | '/api/raffles/$id'
    | '/api/raffles/first-active'
    | '/api/tickets/verify'
    | '/admin/rifas'
    | '/api/purchases'
    | '/api/raffles'
    | '/api/admin/analytics/summary'
    | '/api/admin/emails/$logId'
    | '/api/admin/emails/health'
    | '/api/admin/emails/stats'
    | '/api/admin/me/preferences'
    | '/api/admin/payment-accounts/$id'
    | '/api/admin/purchases/$id'
    | '/api/admin/raffles/$id'
    | '/api/raffles/$id/pause-info'
    | '/api/admin/payment-accounts'
    | '/api/admin/purchases'
    | '/api/admin/raffles'
    | '/api/admin/emails/$logId/resend'
    | '/api/admin/payment-accounts/$id/usage'
    | '/api/admin/purchases/$id/customer'
    | '/api/admin/purchases/$id/emails'
    | '/api/admin/purchases/$id/status'
    | '/api/admin/raffles/$id/auto-pause'
    | '/api/admin/raffles/$id/lifecycle'
    | '/api/admin/raffles/$id/pause'
    | '/api/admin/raffles/$id/promotions'
    | '/api/admin/raffles/$id/publish'
    | '/api/admin/raffles/$id/status'
    | '/api/admin/raffles/$id/unpause'
    | '/api/admin/purchases/$id/emails/send'
    | '/api/admin/purchases/$id/tickets/add'
    | '/api/admin/purchases/$id/tickets/reassign'
    | '/api/admin/purchases/$id/tickets/remove'
    | '/api/admin/raffles/$id/promotions/$promotionId'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/_public/login'
    | '/_public/verificar'
    | '/admin/analytics'
    | '/admin/boletos'
    | '/admin/compras'
    | '/admin/config'
    | '/admin/crear'
    | '/admin/cuenta'
    | '/admin/emails'
    | '/admin/metodos-pago'
    | '/admin/rifas'
    | '/api/config'
    | '/uploads/$'
    | '/_public/'
    | '/admin/'
    | '/_public/rifa/$id'
    | '/admin/edit/$id'
    | '/admin/rifas/$id'
    | '/api/admin/analytics'
    | '/api/admin/config'
    | '/api/admin/dashboard'
    | '/api/admin/emails'
    | '/api/admin/maintenance'
    | '/api/admin/upload'
    | '/api/auth/$'
    | '/api/cron/maintenance'
    | '/api/health/db'
    | '/api/purchase-success/analytics'
    | '/api/purchases/top-clients'
    | '/api/raffles/$id'
    | '/api/raffles/first-active'
    | '/api/tickets/verify'
    | '/admin/rifas/'
    | '/api/purchases/'
    | '/api/raffles/'
    | '/api/admin/analytics/summary'
    | '/api/admin/emails/$logId'
    | '/api/admin/emails/health'
    | '/api/admin/emails/stats'
    | '/api/admin/me/preferences'
    | '/api/admin/payment-accounts/$id'
    | '/api/admin/purchases/$id'
    | '/api/admin/raffles/$id'
    | '/api/raffles/$id/pause-info'
    | '/api/admin/payment-accounts/'
    | '/api/admin/purchases/'
    | '/api/admin/raffles/'
    | '/api/admin/emails/$logId/resend'
    | '/api/admin/payment-accounts/$id/usage'
    | '/api/admin/purchases/$id/customer'
    | '/api/admin/purchases/$id/emails'
    | '/api/admin/purchases/$id/status'
    | '/api/admin/raffles/$id/auto-pause'
    | '/api/admin/raffles/$id/lifecycle'
    | '/api/admin/raffles/$id/pause'
    | '/api/admin/raffles/$id/promotions'
    | '/api/admin/raffles/$id/publish'
    | '/api/admin/raffles/$id/status'
    | '/api/admin/raffles/$id/unpause'
    | '/api/admin/purchases/$id/emails/send'
    | '/api/admin/purchases/$id/tickets/add'
    | '/api/admin/purchases/$id/tickets/reassign'
    | '/api/admin/purchases/$id/tickets/remove'
    | '/api/admin/raffles/$id/promotions/$promotionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ApiConfigRoute: typeof ApiConfigRoute
  UploadsSplatRoute: typeof UploadsSplatRoute
  ApiAdminAnalyticsRoute: typeof ApiAdminAnalyticsRouteWithChildren
  ApiAdminConfigRoute: typeof ApiAdminConfigRoute
  ApiAdminDashboardRoute: typeof ApiAdminDashboardRoute
  ApiAdminEmailsRoute: typeof ApiAdminEmailsRouteWithChildren
  ApiAdminMaintenanceRoute: typeof ApiAdminMaintenanceRoute
  ApiAdminUploadRoute: typeof ApiAdminUploadRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronMaintenanceRoute: typeof ApiCronMaintenanceRoute
  ApiHealthDbRoute: typeof ApiHealthDbRoute
  ApiPurchaseSuccessAnalyticsRoute: typeof ApiPurchaseSuccessAnalyticsRoute
  ApiPurchasesTopClientsRoute: typeof ApiPurchasesTopClientsRoute
  ApiRafflesIdRoute: typeof ApiRafflesIdRouteWithChildren
  ApiRafflesFirstActiveRoute: typeof ApiRafflesFirstActiveRoute
  ApiTicketsVerifyRoute: typeof ApiTicketsVerifyRoute
  ApiPurchasesIndexRoute: typeof ApiPurchasesIndexRoute
  ApiRafflesIndexRoute: typeof ApiRafflesIndexRoute
  ApiAdminMePreferencesRoute: typeof ApiAdminMePreferencesRoute
  ApiAdminPaymentAccountsIdRoute: typeof ApiAdminPaymentAccountsIdRouteWithChildren
  ApiAdminPurchasesIdRoute: typeof ApiAdminPurchasesIdRouteWithChildren
  ApiAdminRafflesIdRoute: typeof ApiAdminRafflesIdRouteWithChildren
  ApiAdminPaymentAccountsIndexRoute: typeof ApiAdminPaymentAccountsIndexRoute
  ApiAdminPurchasesIndexRoute: typeof ApiAdminPurchasesIndexRoute
  ApiAdminRafflesIndexRoute: typeof ApiAdminRafflesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/uploads/$': {
      id: '/uploads/$'
      path: '/uploads/$'
      fullPath: '/uploads/$'
      preLoaderRoute: typeof UploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rifas': {
      id: '/admin/rifas'
      path: '/rifas'
      fullPath: '/admin/rifas'
      preLoaderRoute: typeof AdminRifasRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/metodos-pago': {
      id: '/admin/metodos-pago'
      path: '/metodos-pago'
      fullPath: '/admin/metodos-pago'
      preLoaderRoute: typeof AdminMetodosPagoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cuenta': {
      id: '/admin/cuenta'
      path: '/cuenta'
      fullPath: '/admin/cuenta'
      preLoaderRoute: typeof AdminCuentaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/crear': {
      id: '/admin/crear'
      path: '/crear'
      fullPath: '/admin/crear'
      preLoaderRoute: typeof AdminCrearRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/compras': {
      id: '/admin/compras'
      path: '/compras'
      fullPath: '/admin/compras'
      preLoaderRoute: typeof AdminComprasRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/boletos': {
      id: '/admin/boletos'
      path: '/boletos'
      fullPath: '/admin/boletos'
      preLoaderRoute: typeof AdminBoletosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/verificar': {
      id: '/_public/verificar'
      path: '/verificar'
      fullPath: '/verificar'
      preLoaderRoute: typeof PublicVerificarRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/api/raffles/': {
      id: '/api/raffles/'
      path: '/api/raffles'
      fullPath: '/api/raffles/'
      preLoaderRoute: typeof ApiRafflesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/purchases/': {
      id: '/api/purchases/'
      path: '/api/purchases'
      fullPath: '/api/purchases/'
      preLoaderRoute: typeof ApiPurchasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rifas/': {
      id: '/admin/rifas/'
      path: '/'
      fullPath: '/admin/rifas/'
      preLoaderRoute: typeof AdminRifasIndexRouteImport
      parentRoute: typeof AdminRifasRoute
    }
    '/api/tickets/verify': {
      id: '/api/tickets/verify'
      path: '/api/tickets/verify'
      fullPath: '/api/tickets/verify'
      preLoaderRoute: typeof ApiTicketsVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/raffles/first-active': {
      id: '/api/raffles/first-active'
      path: '/api/raffles/first-active'
      fullPath: '/api/raffles/first-active'
      preLoaderRoute: typeof ApiRafflesFirstActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/raffles/$id': {
      id: '/api/raffles/$id'
      path: '/api/raffles/$id'
      fullPath: '/api/raffles/$id'
      preLoaderRoute: typeof ApiRafflesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/purchases/top-clients': {
      id: '/api/purchases/top-clients'
      path: '/api/purchases/top-clients'
      fullPath: '/api/purchases/top-clients'
      preLoaderRoute: typeof ApiPurchasesTopClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/purchase-success/analytics': {
      id: '/api/purchase-success/analytics'
      path: '/api/purchase-success/analytics'
      fullPath: '/api/purchase-success/analytics'
      preLoaderRoute: typeof ApiPurchaseSuccessAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/db': {
      id: '/api/health/db'
      path: '/api/health/db'
      fullPath: '/api/health/db'
      preLoaderRoute: typeof ApiHealthDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/maintenance': {
      id: '/api/cron/maintenance'
      path: '/api/cron/maintenance'
      fullPath: '/api/cron/maintenance'
      preLoaderRoute: typeof ApiCronMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/upload': {
      id: '/api/admin/upload'
      path: '/api/admin/upload'
      fullPath: '/api/admin/upload'
      preLoaderRoute: typeof ApiAdminUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/maintenance': {
      id: '/api/admin/maintenance'
      path: '/api/admin/maintenance'
      fullPath: '/api/admin/maintenance'
      preLoaderRoute: typeof ApiAdminMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/emails': {
      id: '/api/admin/emails'
      path: '/api/admin/emails'
      fullPath: '/api/admin/emails'
      preLoaderRoute: typeof ApiAdminEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/dashboard': {
      id: '/api/admin/dashboard'
      path: '/api/admin/dashboard'
      fullPath: '/api/admin/dashboard'
      preLoaderRoute: typeof ApiAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/config': {
      id: '/api/admin/config'
      path: '/api/admin/config'
      fullPath: '/api/admin/config'
      preLoaderRoute: typeof ApiAdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/analytics': {
      id: '/api/admin/analytics'
      path: '/api/admin/analytics'
      fullPath: '/api/admin/analytics'
      preLoaderRoute: typeof ApiAdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rifas/$id': {
      id: '/admin/rifas/$id'
      path: '/$id'
      fullPath: '/admin/rifas/$id'
      preLoaderRoute: typeof AdminRifasIdRouteImport
      parentRoute: typeof AdminRifasRoute
    }
    '/admin/edit/$id': {
      id: '/admin/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/edit/$id'
      preLoaderRoute: typeof AdminEditIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_public/rifa/$id': {
      id: '/_public/rifa/$id'
      path: '/rifa/$id'
      fullPath: '/rifa/$id'
      preLoaderRoute: typeof PublicRifaIdRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/api/admin/raffles/': {
      id: '/api/admin/raffles/'
      path: '/api/admin/raffles'
      fullPath: '/api/admin/raffles/'
      preLoaderRoute: typeof ApiAdminRafflesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/purchases/': {
      id: '/api/admin/purchases/'
      path: '/api/admin/purchases'
      fullPath: '/api/admin/purchases/'
      preLoaderRoute: typeof ApiAdminPurchasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/payment-accounts/': {
      id: '/api/admin/payment-accounts/'
      path: '/api/admin/payment-accounts'
      fullPath: '/api/admin/payment-accounts/'
      preLoaderRoute: typeof ApiAdminPaymentAccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/raffles/$id/pause-info': {
      id: '/api/raffles/$id/pause-info'
      path: '/pause-info'
      fullPath: '/api/raffles/$id/pause-info'
      preLoaderRoute: typeof ApiRafflesIdPauseInfoRouteImport
      parentRoute: typeof ApiRafflesIdRoute
    }
    '/api/admin/raffles/$id': {
      id: '/api/admin/raffles/$id'
      path: '/api/admin/raffles/$id'
      fullPath: '/api/admin/raffles/$id'
      preLoaderRoute: typeof ApiAdminRafflesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/purchases/$id': {
      id: '/api/admin/purchases/$id'
      path: '/api/admin/purchases/$id'
      fullPath: '/api/admin/purchases/$id'
      preLoaderRoute: typeof ApiAdminPurchasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/payment-accounts/$id': {
      id: '/api/admin/payment-accounts/$id'
      path: '/api/admin/payment-accounts/$id'
      fullPath: '/api/admin/payment-accounts/$id'
      preLoaderRoute: typeof ApiAdminPaymentAccountsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/me/preferences': {
      id: '/api/admin/me/preferences'
      path: '/api/admin/me/preferences'
      fullPath: '/api/admin/me/preferences'
      preLoaderRoute: typeof ApiAdminMePreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/emails/stats': {
      id: '/api/admin/emails/stats'
      path: '/stats'
      fullPath: '/api/admin/emails/stats'
      preLoaderRoute: typeof ApiAdminEmailsStatsRouteImport
      parentRoute: typeof ApiAdminEmailsRoute
    }
    '/api/admin/emails/health': {
      id: '/api/admin/emails/health'
      path: '/health'
      fullPath: '/api/admin/emails/health'
      preLoaderRoute: typeof ApiAdminEmailsHealthRouteImport
      parentRoute: typeof ApiAdminEmailsRoute
    }
    '/api/admin/emails/$logId': {
      id: '/api/admin/emails/$logId'
      path: '/$logId'
      fullPath: '/api/admin/emails/$logId'
      preLoaderRoute: typeof ApiAdminEmailsLogIdRouteImport
      parentRoute: typeof ApiAdminEmailsRoute
    }
    '/api/admin/analytics/summary': {
      id: '/api/admin/analytics/summary'
      path: '/summary'
      fullPath: '/api/admin/analytics/summary'
      preLoaderRoute: typeof ApiAdminAnalyticsSummaryRouteImport
      parentRoute: typeof ApiAdminAnalyticsRoute
    }
    '/api/admin/raffles/$id/unpause': {
      id: '/api/admin/raffles/$id/unpause'
      path: '/unpause'
      fullPath: '/api/admin/raffles/$id/unpause'
      preLoaderRoute: typeof ApiAdminRafflesIdUnpauseRouteImport
      parentRoute: typeof ApiAdminRafflesIdRoute
    }
    '/api/admin/raffles/$id/status': {
      id: '/api/admin/raffles/$id/status'
      path: '/status'
      fullPath: '/api/admin/raffles/$id/status'
      preLoaderRoute: typeof ApiAdminRafflesIdStatusRouteImport
      parentRoute: typeof ApiAdminRafflesIdRoute
    }
    '/api/admin/raffles/$id/publish': {
      id: '/api/admin/raffles/$id/publish'
      path: '/publish'
      fullPath: '/api/admin/raffles/$id/publish'
      preLoaderRoute: typeof ApiAdminRafflesIdPublishRouteImport
      parentRoute: typeof ApiAdminRafflesIdRoute
    }
    '/api/admin/raffles/$id/promotions': {
      id: '/api/admin/raffles/$id/promotions'
      path: '/promotions'
      fullPath: '/api/admin/raffles/$id/promotions'
      preLoaderRoute: typeof ApiAdminRafflesIdPromotionsRouteImport
      parentRoute: typeof ApiAdminRafflesIdRoute
    }
    '/api/admin/raffles/$id/pause': {
      id: '/api/admin/raffles/$id/pause'
      path: '/pause'
      fullPath: '/api/admin/raffles/$id/pause'
      preLoaderRoute: typeof ApiAdminRafflesIdPauseRouteImport
      parentRoute: typeof ApiAdminRafflesIdRoute
    }
    '/api/admin/raffles/$id/lifecycle': {
      id: '/api/admin/raffles/$id/lifecycle'
      path: '/lifecycle'
      fullPath: '/api/admin/raffles/$id/lifecycle'
      preLoaderRoute: typeof ApiAdminRafflesIdLifecycleRouteImport
      parentRoute: typeof ApiAdminRafflesIdRoute
    }
    '/api/admin/raffles/$id/auto-pause': {
      id: '/api/admin/raffles/$id/auto-pause'
      path: '/auto-pause'
      fullPath: '/api/admin/raffles/$id/auto-pause'
      preLoaderRoute: typeof ApiAdminRafflesIdAutoPauseRouteImport
      parentRoute: typeof ApiAdminRafflesIdRoute
    }
    '/api/admin/purchases/$id/status': {
      id: '/api/admin/purchases/$id/status'
      path: '/status'
      fullPath: '/api/admin/purchases/$id/status'
      preLoaderRoute: typeof ApiAdminPurchasesIdStatusRouteImport
      parentRoute: typeof ApiAdminPurchasesIdRoute
    }
    '/api/admin/purchases/$id/emails': {
      id: '/api/admin/purchases/$id/emails'
      path: '/emails'
      fullPath: '/api/admin/purchases/$id/emails'
      preLoaderRoute: typeof ApiAdminPurchasesIdEmailsRouteImport
      parentRoute: typeof ApiAdminPurchasesIdRoute
    }
    '/api/admin/purchases/$id/customer': {
      id: '/api/admin/purchases/$id/customer'
      path: '/customer'
      fullPath: '/api/admin/purchases/$id/customer'
      preLoaderRoute: typeof ApiAdminPurchasesIdCustomerRouteImport
      parentRoute: typeof ApiAdminPurchasesIdRoute
    }
    '/api/admin/payment-accounts/$id/usage': {
      id: '/api/admin/payment-accounts/$id/usage'
      path: '/usage'
      fullPath: '/api/admin/payment-accounts/$id/usage'
      preLoaderRoute: typeof ApiAdminPaymentAccountsIdUsageRouteImport
      parentRoute: typeof ApiAdminPaymentAccountsIdRoute
    }
    '/api/admin/emails/$logId/resend': {
      id: '/api/admin/emails/$logId/resend'
      path: '/resend'
      fullPath: '/api/admin/emails/$logId/resend'
      preLoaderRoute: typeof ApiAdminEmailsLogIdResendRouteImport
      parentRoute: typeof ApiAdminEmailsLogIdRoute
    }
    '/api/admin/raffles/$id/promotions/$promotionId': {
      id: '/api/admin/raffles/$id/promotions/$promotionId'
      path: '/$promotionId'
      fullPath: '/api/admin/raffles/$id/promotions/$promotionId'
      preLoaderRoute: typeof ApiAdminRafflesIdPromotionsPromotionIdRouteImport
      parentRoute: typeof ApiAdminRafflesIdPromotionsRoute
    }
    '/api/admin/purchases/$id/tickets/remove': {
      id: '/api/admin/purchases/$id/tickets/remove'
      path: '/tickets/remove'
      fullPath: '/api/admin/purchases/$id/tickets/remove'
      preLoaderRoute: typeof ApiAdminPurchasesIdTicketsRemoveRouteImport
      parentRoute: typeof ApiAdminPurchasesIdRoute
    }
    '/api/admin/purchases/$id/tickets/reassign': {
      id: '/api/admin/purchases/$id/tickets/reassign'
      path: '/tickets/reassign'
      fullPath: '/api/admin/purchases/$id/tickets/reassign'
      preLoaderRoute: typeof ApiAdminPurchasesIdTicketsReassignRouteImport
      parentRoute: typeof ApiAdminPurchasesIdRoute
    }
    '/api/admin/purchases/$id/tickets/add': {
      id: '/api/admin/purchases/$id/tickets/add'
      path: '/tickets/add'
      fullPath: '/api/admin/purchases/$id/tickets/add'
      preLoaderRoute: typeof ApiAdminPurchasesIdTicketsAddRouteImport
      parentRoute: typeof ApiAdminPurchasesIdRoute
    }
    '/api/admin/purchases/$id/emails/send': {
      id: '/api/admin/purchases/$id/emails/send'
      path: '/send'
      fullPath: '/api/admin/purchases/$id/emails/send'
      preLoaderRoute: typeof ApiAdminPurchasesIdEmailsSendRouteImport
      parentRoute: typeof ApiAdminPurchasesIdEmailsRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicVerificarRoute: typeof PublicVerificarRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicRifaIdRoute: typeof PublicRifaIdRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicVerificarRoute: PublicVerificarRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicRifaIdRoute: PublicRifaIdRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AdminRifasRouteChildren {
  AdminRifasIdRoute: typeof AdminRifasIdRoute
  AdminRifasIndexRoute: typeof AdminRifasIndexRoute
}

const AdminRifasRouteChildren: AdminRifasRouteChildren = {
  AdminRifasIdRoute: AdminRifasIdRoute,
  AdminRifasIndexRoute: AdminRifasIndexRoute,
}

const AdminRifasRouteWithChildren = AdminRifasRoute._addFileChildren(
  AdminRifasRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBoletosRoute: typeof AdminBoletosRoute
  AdminComprasRoute: typeof AdminComprasRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminCrearRoute: typeof AdminCrearRoute
  AdminCuentaRoute: typeof AdminCuentaRoute
  AdminEmailsRoute: typeof AdminEmailsRoute
  AdminMetodosPagoRoute: typeof AdminMetodosPagoRoute
  AdminRifasRoute: typeof AdminRifasRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEditIdRoute: typeof AdminEditIdRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBoletosRoute: AdminBoletosRoute,
  AdminComprasRoute: AdminComprasRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminCrearRoute: AdminCrearRoute,
  AdminCuentaRoute: AdminCuentaRoute,
  AdminEmailsRoute: AdminEmailsRoute,
  AdminMetodosPagoRoute: AdminMetodosPagoRoute,
  AdminRifasRoute: AdminRifasRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminEditIdRoute: AdminEditIdRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ApiAdminAnalyticsRouteChildren {
  ApiAdminAnalyticsSummaryRoute: typeof ApiAdminAnalyticsSummaryRoute
}

const ApiAdminAnalyticsRouteChildren: ApiAdminAnalyticsRouteChildren = {
  ApiAdminAnalyticsSummaryRoute: ApiAdminAnalyticsSummaryRoute,
}

const ApiAdminAnalyticsRouteWithChildren =
  ApiAdminAnalyticsRoute._addFileChildren(ApiAdminAnalyticsRouteChildren)

interface ApiAdminEmailsLogIdRouteChildren {
  ApiAdminEmailsLogIdResendRoute: typeof ApiAdminEmailsLogIdResendRoute
}

const ApiAdminEmailsLogIdRouteChildren: ApiAdminEmailsLogIdRouteChildren = {
  ApiAdminEmailsLogIdResendRoute: ApiAdminEmailsLogIdResendRoute,
}

const ApiAdminEmailsLogIdRouteWithChildren =
  ApiAdminEmailsLogIdRoute._addFileChildren(ApiAdminEmailsLogIdRouteChildren)

interface ApiAdminEmailsRouteChildren {
  ApiAdminEmailsLogIdRoute: typeof ApiAdminEmailsLogIdRouteWithChildren
  ApiAdminEmailsHealthRoute: typeof ApiAdminEmailsHealthRoute
  ApiAdminEmailsStatsRoute: typeof ApiAdminEmailsStatsRoute
}

const ApiAdminEmailsRouteChildren: ApiAdminEmailsRouteChildren = {
  ApiAdminEmailsLogIdRoute: ApiAdminEmailsLogIdRouteWithChildren,
  ApiAdminEmailsHealthRoute: ApiAdminEmailsHealthRoute,
  ApiAdminEmailsStatsRoute: ApiAdminEmailsStatsRoute,
}

const ApiAdminEmailsRouteWithChildren = ApiAdminEmailsRoute._addFileChildren(
  ApiAdminEmailsRouteChildren,
)

interface ApiRafflesIdRouteChildren {
  ApiRafflesIdPauseInfoRoute: typeof ApiRafflesIdPauseInfoRoute
}

const ApiRafflesIdRouteChildren: ApiRafflesIdRouteChildren = {
  ApiRafflesIdPauseInfoRoute: ApiRafflesIdPauseInfoRoute,
}

const ApiRafflesIdRouteWithChildren = ApiRafflesIdRoute._addFileChildren(
  ApiRafflesIdRouteChildren,
)

interface ApiAdminPaymentAccountsIdRouteChildren {
  ApiAdminPaymentAccountsIdUsageRoute: typeof ApiAdminPaymentAccountsIdUsageRoute
}

const ApiAdminPaymentAccountsIdRouteChildren: ApiAdminPaymentAccountsIdRouteChildren =
  {
    ApiAdminPaymentAccountsIdUsageRoute: ApiAdminPaymentAccountsIdUsageRoute,
  }

const ApiAdminPaymentAccountsIdRouteWithChildren =
  ApiAdminPaymentAccountsIdRoute._addFileChildren(
    ApiAdminPaymentAccountsIdRouteChildren,
  )

interface ApiAdminPurchasesIdEmailsRouteChildren {
  ApiAdminPurchasesIdEmailsSendRoute: typeof ApiAdminPurchasesIdEmailsSendRoute
}

const ApiAdminPurchasesIdEmailsRouteChildren: ApiAdminPurchasesIdEmailsRouteChildren =
  {
    ApiAdminPurchasesIdEmailsSendRoute: ApiAdminPurchasesIdEmailsSendRoute,
  }

const ApiAdminPurchasesIdEmailsRouteWithChildren =
  ApiAdminPurchasesIdEmailsRoute._addFileChildren(
    ApiAdminPurchasesIdEmailsRouteChildren,
  )

interface ApiAdminPurchasesIdRouteChildren {
  ApiAdminPurchasesIdCustomerRoute: typeof ApiAdminPurchasesIdCustomerRoute
  ApiAdminPurchasesIdEmailsRoute: typeof ApiAdminPurchasesIdEmailsRouteWithChildren
  ApiAdminPurchasesIdStatusRoute: typeof ApiAdminPurchasesIdStatusRoute
  ApiAdminPurchasesIdTicketsAddRoute: typeof ApiAdminPurchasesIdTicketsAddRoute
  ApiAdminPurchasesIdTicketsReassignRoute: typeof ApiAdminPurchasesIdTicketsReassignRoute
  ApiAdminPurchasesIdTicketsRemoveRoute: typeof ApiAdminPurchasesIdTicketsRemoveRoute
}

const ApiAdminPurchasesIdRouteChildren: ApiAdminPurchasesIdRouteChildren = {
  ApiAdminPurchasesIdCustomerRoute: ApiAdminPurchasesIdCustomerRoute,
  ApiAdminPurchasesIdEmailsRoute: ApiAdminPurchasesIdEmailsRouteWithChildren,
  ApiAdminPurchasesIdStatusRoute: ApiAdminPurchasesIdStatusRoute,
  ApiAdminPurchasesIdTicketsAddRoute: ApiAdminPurchasesIdTicketsAddRoute,
  ApiAdminPurchasesIdTicketsReassignRoute:
    ApiAdminPurchasesIdTicketsReassignRoute,
  ApiAdminPurchasesIdTicketsRemoveRoute: ApiAdminPurchasesIdTicketsRemoveRoute,
}

const ApiAdminPurchasesIdRouteWithChildren =
  ApiAdminPurchasesIdRoute._addFileChildren(ApiAdminPurchasesIdRouteChildren)

interface ApiAdminRafflesIdPromotionsRouteChildren {
  ApiAdminRafflesIdPromotionsPromotionIdRoute: typeof ApiAdminRafflesIdPromotionsPromotionIdRoute
}

const ApiAdminRafflesIdPromotionsRouteChildren: ApiAdminRafflesIdPromotionsRouteChildren =
  {
    ApiAdminRafflesIdPromotionsPromotionIdRoute:
      ApiAdminRafflesIdPromotionsPromotionIdRoute,
  }

const ApiAdminRafflesIdPromotionsRouteWithChildren =
  ApiAdminRafflesIdPromotionsRoute._addFileChildren(
    ApiAdminRafflesIdPromotionsRouteChildren,
  )

interface ApiAdminRafflesIdRouteChildren {
  ApiAdminRafflesIdAutoPauseRoute: typeof ApiAdminRafflesIdAutoPauseRoute
  ApiAdminRafflesIdLifecycleRoute: typeof ApiAdminRafflesIdLifecycleRoute
  ApiAdminRafflesIdPauseRoute: typeof ApiAdminRafflesIdPauseRoute
  ApiAdminRafflesIdPromotionsRoute: typeof ApiAdminRafflesIdPromotionsRouteWithChildren
  ApiAdminRafflesIdPublishRoute: typeof ApiAdminRafflesIdPublishRoute
  ApiAdminRafflesIdStatusRoute: typeof ApiAdminRafflesIdStatusRoute
  ApiAdminRafflesIdUnpauseRoute: typeof ApiAdminRafflesIdUnpauseRoute
}

const ApiAdminRafflesIdRouteChildren: ApiAdminRafflesIdRouteChildren = {
  ApiAdminRafflesIdAutoPauseRoute: ApiAdminRafflesIdAutoPauseRoute,
  ApiAdminRafflesIdLifecycleRoute: ApiAdminRafflesIdLifecycleRoute,
  ApiAdminRafflesIdPauseRoute: ApiAdminRafflesIdPauseRoute,
  ApiAdminRafflesIdPromotionsRoute:
    ApiAdminRafflesIdPromotionsRouteWithChildren,
  ApiAdminRafflesIdPublishRoute: ApiAdminRafflesIdPublishRoute,
  ApiAdminRafflesIdStatusRoute: ApiAdminRafflesIdStatusRoute,
  ApiAdminRafflesIdUnpauseRoute: ApiAdminRafflesIdUnpauseRoute,
}

const ApiAdminRafflesIdRouteWithChildren =
  ApiAdminRafflesIdRoute._addFileChildren(ApiAdminRafflesIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ApiConfigRoute: ApiConfigRoute,
  UploadsSplatRoute: UploadsSplatRoute,
  ApiAdminAnalyticsRoute: ApiAdminAnalyticsRouteWithChildren,
  ApiAdminConfigRoute: ApiAdminConfigRoute,
  ApiAdminDashboardRoute: ApiAdminDashboardRoute,
  ApiAdminEmailsRoute: ApiAdminEmailsRouteWithChildren,
  ApiAdminMaintenanceRoute: ApiAdminMaintenanceRoute,
  ApiAdminUploadRoute: ApiAdminUploadRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronMaintenanceRoute: ApiCronMaintenanceRoute,
  ApiHealthDbRoute: ApiHealthDbRoute,
  ApiPurchaseSuccessAnalyticsRoute: ApiPurchaseSuccessAnalyticsRoute,
  ApiPurchasesTopClientsRoute: ApiPurchasesTopClientsRoute,
  ApiRafflesIdRoute: ApiRafflesIdRouteWithChildren,
  ApiRafflesFirstActiveRoute: ApiRafflesFirstActiveRoute,
  ApiTicketsVerifyRoute: ApiTicketsVerifyRoute,
  ApiPurchasesIndexRoute: ApiPurchasesIndexRoute,
  ApiRafflesIndexRoute: ApiRafflesIndexRoute,
  ApiAdminMePreferencesRoute: ApiAdminMePreferencesRoute,
  ApiAdminPaymentAccountsIdRoute: ApiAdminPaymentAccountsIdRouteWithChildren,
  ApiAdminPurchasesIdRoute: ApiAdminPurchasesIdRouteWithChildren,
  ApiAdminRafflesIdRoute: ApiAdminRafflesIdRouteWithChildren,
  ApiAdminPaymentAccountsIndexRoute: ApiAdminPaymentAccountsIndexRoute,
  ApiAdminPurchasesIndexRoute: ApiAdminPurchasesIndexRoute,
  ApiAdminRafflesIndexRoute: ApiAdminRafflesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
