/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificarRouteImport } from './routes/verificar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RifaIdRouteImport } from './routes/rifa/$id'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as AdminRifasRouteImport } from './routes/admin/rifas'
import { Route as AdminEmailsRouteImport } from './routes/admin/emails'
import { Route as AdminCrearRouteImport } from './routes/admin/crear'
import { Route as AdminConfigRouteImport } from './routes/admin/config'
import { Route as AdminBoletosRouteImport } from './routes/admin/boletos'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as ApiRafflesIndexRouteImport } from './routes/api/raffles/index'
import { Route as ApiPurchasesIndexRouteImport } from './routes/api/purchases/index'
import { Route as ApiTicketsVerifyRouteImport } from './routes/api/tickets.verify'
import { Route as ApiRafflesPublishedRouteImport } from './routes/api/raffles/published'
import { Route as ApiRafflesFirstActiveRouteImport } from './routes/api/raffles/first-active'
import { Route as ApiRafflesIdRouteImport } from './routes/api/raffles/$id'
import { Route as ApiPurchasesTopClientsRouteImport } from './routes/api/purchases.top-clients'
import { Route as ApiHealthDbRouteImport } from './routes/api/health/db'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminDashboardRouteImport } from './routes/api/admin/dashboard'
import { Route as ApiAdminConfigRouteImport } from './routes/api/admin/config'
import { Route as ApiAdminRafflesIndexRouteImport } from './routes/api/admin/raffles/index'
import { Route as ApiAdminPurchasesIndexRouteImport } from './routes/api/admin/purchases/index'
import { Route as ApiRafflesIdPauseInfoRouteImport } from './routes/api/raffles/$id.pause-info'
import { Route as ApiAdminRafflesIdRouteImport } from './routes/api/admin/raffles/$id'
import { Route as ApiAdminPurchasesIdRouteImport } from './routes/api/admin/purchases/$id'
import { Route as ApiAdminRafflesIdUnpauseRouteImport } from './routes/api/admin/raffles/$id.unpause'
import { Route as ApiAdminRafflesIdPublishRouteImport } from './routes/api/admin/raffles/$id.publish'
import { Route as ApiAdminRafflesIdPauseRouteImport } from './routes/api/admin/raffles/$id.pause'
import { Route as ApiAdminRafflesIdAutoPauseRouteImport } from './routes/api/admin/raffles/$id.auto-pause'
import { Route as ApiAdminPurchasesIdStatusRouteImport } from './routes/api/admin/purchases/$id.status'
import { Route as ApiAdminPurchasesIdTicketsRemoveRouteImport } from './routes/api/admin/purchases/$id.tickets.remove'
import { Route as ApiAdminPurchasesIdTicketsReassignRouteImport } from './routes/api/admin/purchases/$id.tickets.reassign'
import { Route as ApiAdminPurchasesIdTicketsAddRouteImport } from './routes/api/admin/purchases/$id.tickets.add'

const VerificarRoute = VerificarRouteImport.update({
  id: '/verificar',
  path: '/verificar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const RifaIdRoute = RifaIdRouteImport.update({
  id: '/rifa/$id',
  path: '/rifa/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRifasRoute = AdminRifasRouteImport.update({
  id: '/rifas',
  path: '/rifas',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCrearRoute = AdminCrearRouteImport.update({
  id: '/crear',
  path: '/crear',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBoletosRoute = AdminBoletosRouteImport.update({
  id: '/boletos',
  path: '/boletos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiRafflesIndexRoute = ApiRafflesIndexRouteImport.update({
  id: '/api/raffles/',
  path: '/api/raffles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPurchasesIndexRoute = ApiPurchasesIndexRouteImport.update({
  id: '/api/purchases/',
  path: '/api/purchases/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTicketsVerifyRoute = ApiTicketsVerifyRouteImport.update({
  id: '/api/tickets/verify',
  path: '/api/tickets/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRafflesPublishedRoute = ApiRafflesPublishedRouteImport.update({
  id: '/api/raffles/published',
  path: '/api/raffles/published',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRafflesFirstActiveRoute = ApiRafflesFirstActiveRouteImport.update({
  id: '/api/raffles/first-active',
  path: '/api/raffles/first-active',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRafflesIdRoute = ApiRafflesIdRouteImport.update({
  id: '/api/raffles/$id',
  path: '/api/raffles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPurchasesTopClientsRoute = ApiPurchasesTopClientsRouteImport.update({
  id: '/api/purchases/top-clients',
  path: '/api/purchases/top-clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthDbRoute = ApiHealthDbRouteImport.update({
  id: '/api/health/db',
  path: '/api/health/db',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDashboardRoute = ApiAdminDashboardRouteImport.update({
  id: '/api/admin/dashboard',
  path: '/api/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminConfigRoute = ApiAdminConfigRouteImport.update({
  id: '/api/admin/config',
  path: '/api/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRafflesIndexRoute = ApiAdminRafflesIndexRouteImport.update({
  id: '/api/admin/raffles/',
  path: '/api/admin/raffles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPurchasesIndexRoute = ApiAdminPurchasesIndexRouteImport.update({
  id: '/api/admin/purchases/',
  path: '/api/admin/purchases/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRafflesIdPauseInfoRoute = ApiRafflesIdPauseInfoRouteImport.update({
  id: '/pause-info',
  path: '/pause-info',
  getParentRoute: () => ApiRafflesIdRoute,
} as any)
const ApiAdminRafflesIdRoute = ApiAdminRafflesIdRouteImport.update({
  id: '/api/admin/raffles/$id',
  path: '/api/admin/raffles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPurchasesIdRoute = ApiAdminPurchasesIdRouteImport.update({
  id: '/api/admin/purchases/$id',
  path: '/api/admin/purchases/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRafflesIdUnpauseRoute =
  ApiAdminRafflesIdUnpauseRouteImport.update({
    id: '/unpause',
    path: '/unpause',
    getParentRoute: () => ApiAdminRafflesIdRoute,
  } as any)
const ApiAdminRafflesIdPublishRoute =
  ApiAdminRafflesIdPublishRouteImport.update({
    id: '/publish',
    path: '/publish',
    getParentRoute: () => ApiAdminRafflesIdRoute,
  } as any)
const ApiAdminRafflesIdPauseRoute = ApiAdminRafflesIdPauseRouteImport.update({
  id: '/pause',
  path: '/pause',
  getParentRoute: () => ApiAdminRafflesIdRoute,
} as any)
const ApiAdminRafflesIdAutoPauseRoute =
  ApiAdminRafflesIdAutoPauseRouteImport.update({
    id: '/auto-pause',
    path: '/auto-pause',
    getParentRoute: () => ApiAdminRafflesIdRoute,
  } as any)
const ApiAdminPurchasesIdStatusRoute =
  ApiAdminPurchasesIdStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => ApiAdminPurchasesIdRoute,
  } as any)
const ApiAdminPurchasesIdTicketsRemoveRoute =
  ApiAdminPurchasesIdTicketsRemoveRouteImport.update({
    id: '/tickets/remove',
    path: '/tickets/remove',
    getParentRoute: () => ApiAdminPurchasesIdRoute,
  } as any)
const ApiAdminPurchasesIdTicketsReassignRoute =
  ApiAdminPurchasesIdTicketsReassignRouteImport.update({
    id: '/tickets/reassign',
    path: '/tickets/reassign',
    getParentRoute: () => ApiAdminPurchasesIdRoute,
  } as any)
const ApiAdminPurchasesIdTicketsAddRoute =
  ApiAdminPurchasesIdTicketsAddRouteImport.update({
    id: '/tickets/add',
    path: '/tickets/add',
    getParentRoute: () => ApiAdminPurchasesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/verificar': typeof VerificarRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/boletos': typeof AdminBoletosRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/crear': typeof AdminCrearRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/rifas': typeof AdminRifasRoute
  '/api/config': typeof ApiConfigRoute
  '/rifa/$id': typeof RifaIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/config': typeof ApiAdminConfigRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/db': typeof ApiHealthDbRoute
  '/api/purchases/top-clients': typeof ApiPurchasesTopClientsRoute
  '/api/raffles/$id': typeof ApiRafflesIdRouteWithChildren
  '/api/raffles/first-active': typeof ApiRafflesFirstActiveRoute
  '/api/raffles/published': typeof ApiRafflesPublishedRoute
  '/api/tickets/verify': typeof ApiTicketsVerifyRoute
  '/api/purchases/': typeof ApiPurchasesIndexRoute
  '/api/raffles/': typeof ApiRafflesIndexRoute
  '/api/admin/purchases/$id': typeof ApiAdminPurchasesIdRouteWithChildren
  '/api/admin/raffles/$id': typeof ApiAdminRafflesIdRouteWithChildren
  '/api/raffles/$id/pause-info': typeof ApiRafflesIdPauseInfoRoute
  '/api/admin/purchases/': typeof ApiAdminPurchasesIndexRoute
  '/api/admin/raffles/': typeof ApiAdminRafflesIndexRoute
  '/api/admin/purchases/$id/status': typeof ApiAdminPurchasesIdStatusRoute
  '/api/admin/raffles/$id/auto-pause': typeof ApiAdminRafflesIdAutoPauseRoute
  '/api/admin/raffles/$id/pause': typeof ApiAdminRafflesIdPauseRoute
  '/api/admin/raffles/$id/publish': typeof ApiAdminRafflesIdPublishRoute
  '/api/admin/raffles/$id/unpause': typeof ApiAdminRafflesIdUnpauseRoute
  '/api/admin/purchases/$id/tickets/add': typeof ApiAdminPurchasesIdTicketsAddRoute
  '/api/admin/purchases/$id/tickets/reassign': typeof ApiAdminPurchasesIdTicketsReassignRoute
  '/api/admin/purchases/$id/tickets/remove': typeof ApiAdminPurchasesIdTicketsRemoveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/verificar': typeof VerificarRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/boletos': typeof AdminBoletosRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/crear': typeof AdminCrearRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/rifas': typeof AdminRifasRoute
  '/api/config': typeof ApiConfigRoute
  '/rifa/$id': typeof RifaIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/admin/config': typeof ApiAdminConfigRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/db': typeof ApiHealthDbRoute
  '/api/purchases/top-clients': typeof ApiPurchasesTopClientsRoute
  '/api/raffles/$id': typeof ApiRafflesIdRouteWithChildren
  '/api/raffles/first-active': typeof ApiRafflesFirstActiveRoute
  '/api/raffles/published': typeof ApiRafflesPublishedRoute
  '/api/tickets/verify': typeof ApiTicketsVerifyRoute
  '/api/purchases': typeof ApiPurchasesIndexRoute
  '/api/raffles': typeof ApiRafflesIndexRoute
  '/api/admin/purchases/$id': typeof ApiAdminPurchasesIdRouteWithChildren
  '/api/admin/raffles/$id': typeof ApiAdminRafflesIdRouteWithChildren
  '/api/raffles/$id/pause-info': typeof ApiRafflesIdPauseInfoRoute
  '/api/admin/purchases': typeof ApiAdminPurchasesIndexRoute
  '/api/admin/raffles': typeof ApiAdminRafflesIndexRoute
  '/api/admin/purchases/$id/status': typeof ApiAdminPurchasesIdStatusRoute
  '/api/admin/raffles/$id/auto-pause': typeof ApiAdminRafflesIdAutoPauseRoute
  '/api/admin/raffles/$id/pause': typeof ApiAdminRafflesIdPauseRoute
  '/api/admin/raffles/$id/publish': typeof ApiAdminRafflesIdPublishRoute
  '/api/admin/raffles/$id/unpause': typeof ApiAdminRafflesIdUnpauseRoute
  '/api/admin/purchases/$id/tickets/add': typeof ApiAdminPurchasesIdTicketsAddRoute
  '/api/admin/purchases/$id/tickets/reassign': typeof ApiAdminPurchasesIdTicketsReassignRoute
  '/api/admin/purchases/$id/tickets/remove': typeof ApiAdminPurchasesIdTicketsRemoveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/verificar': typeof VerificarRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/boletos': typeof AdminBoletosRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/crear': typeof AdminCrearRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/rifas': typeof AdminRifasRoute
  '/api/config': typeof ApiConfigRoute
  '/rifa/$id': typeof RifaIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/config': typeof ApiAdminConfigRoute
  '/api/admin/dashboard': typeof ApiAdminDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/health/db': typeof ApiHealthDbRoute
  '/api/purchases/top-clients': typeof ApiPurchasesTopClientsRoute
  '/api/raffles/$id': typeof ApiRafflesIdRouteWithChildren
  '/api/raffles/first-active': typeof ApiRafflesFirstActiveRoute
  '/api/raffles/published': typeof ApiRafflesPublishedRoute
  '/api/tickets/verify': typeof ApiTicketsVerifyRoute
  '/api/purchases/': typeof ApiPurchasesIndexRoute
  '/api/raffles/': typeof ApiRafflesIndexRoute
  '/api/admin/purchases/$id': typeof ApiAdminPurchasesIdRouteWithChildren
  '/api/admin/raffles/$id': typeof ApiAdminRafflesIdRouteWithChildren
  '/api/raffles/$id/pause-info': typeof ApiRafflesIdPauseInfoRoute
  '/api/admin/purchases/': typeof ApiAdminPurchasesIndexRoute
  '/api/admin/raffles/': typeof ApiAdminRafflesIndexRoute
  '/api/admin/purchases/$id/status': typeof ApiAdminPurchasesIdStatusRoute
  '/api/admin/raffles/$id/auto-pause': typeof ApiAdminRafflesIdAutoPauseRoute
  '/api/admin/raffles/$id/pause': typeof ApiAdminRafflesIdPauseRoute
  '/api/admin/raffles/$id/publish': typeof ApiAdminRafflesIdPublishRoute
  '/api/admin/raffles/$id/unpause': typeof ApiAdminRafflesIdUnpauseRoute
  '/api/admin/purchases/$id/tickets/add': typeof ApiAdminPurchasesIdTicketsAddRoute
  '/api/admin/purchases/$id/tickets/reassign': typeof ApiAdminPurchasesIdTicketsReassignRoute
  '/api/admin/purchases/$id/tickets/remove': typeof ApiAdminPurchasesIdTicketsRemoveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/verificar'
    | '/admin/analytics'
    | '/admin/boletos'
    | '/admin/config'
    | '/admin/crear'
    | '/admin/emails'
    | '/admin/rifas'
    | '/api/config'
    | '/rifa/$id'
    | '/admin/'
    | '/api/admin/config'
    | '/api/admin/dashboard'
    | '/api/auth/$'
    | '/api/health/db'
    | '/api/purchases/top-clients'
    | '/api/raffles/$id'
    | '/api/raffles/first-active'
    | '/api/raffles/published'
    | '/api/tickets/verify'
    | '/api/purchases/'
    | '/api/raffles/'
    | '/api/admin/purchases/$id'
    | '/api/admin/raffles/$id'
    | '/api/raffles/$id/pause-info'
    | '/api/admin/purchases/'
    | '/api/admin/raffles/'
    | '/api/admin/purchases/$id/status'
    | '/api/admin/raffles/$id/auto-pause'
    | '/api/admin/raffles/$id/pause'
    | '/api/admin/raffles/$id/publish'
    | '/api/admin/raffles/$id/unpause'
    | '/api/admin/purchases/$id/tickets/add'
    | '/api/admin/purchases/$id/tickets/reassign'
    | '/api/admin/purchases/$id/tickets/remove'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/verificar'
    | '/admin/analytics'
    | '/admin/boletos'
    | '/admin/config'
    | '/admin/crear'
    | '/admin/emails'
    | '/admin/rifas'
    | '/api/config'
    | '/rifa/$id'
    | '/admin'
    | '/api/admin/config'
    | '/api/admin/dashboard'
    | '/api/auth/$'
    | '/api/health/db'
    | '/api/purchases/top-clients'
    | '/api/raffles/$id'
    | '/api/raffles/first-active'
    | '/api/raffles/published'
    | '/api/tickets/verify'
    | '/api/purchases'
    | '/api/raffles'
    | '/api/admin/purchases/$id'
    | '/api/admin/raffles/$id'
    | '/api/raffles/$id/pause-info'
    | '/api/admin/purchases'
    | '/api/admin/raffles'
    | '/api/admin/purchases/$id/status'
    | '/api/admin/raffles/$id/auto-pause'
    | '/api/admin/raffles/$id/pause'
    | '/api/admin/raffles/$id/publish'
    | '/api/admin/raffles/$id/unpause'
    | '/api/admin/purchases/$id/tickets/add'
    | '/api/admin/purchases/$id/tickets/reassign'
    | '/api/admin/purchases/$id/tickets/remove'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/verificar'
    | '/admin/analytics'
    | '/admin/boletos'
    | '/admin/config'
    | '/admin/crear'
    | '/admin/emails'
    | '/admin/rifas'
    | '/api/config'
    | '/rifa/$id'
    | '/admin/'
    | '/api/admin/config'
    | '/api/admin/dashboard'
    | '/api/auth/$'
    | '/api/health/db'
    | '/api/purchases/top-clients'
    | '/api/raffles/$id'
    | '/api/raffles/first-active'
    | '/api/raffles/published'
    | '/api/tickets/verify'
    | '/api/purchases/'
    | '/api/raffles/'
    | '/api/admin/purchases/$id'
    | '/api/admin/raffles/$id'
    | '/api/raffles/$id/pause-info'
    | '/api/admin/purchases/'
    | '/api/admin/raffles/'
    | '/api/admin/purchases/$id/status'
    | '/api/admin/raffles/$id/auto-pause'
    | '/api/admin/raffles/$id/pause'
    | '/api/admin/raffles/$id/publish'
    | '/api/admin/raffles/$id/unpause'
    | '/api/admin/purchases/$id/tickets/add'
    | '/api/admin/purchases/$id/tickets/reassign'
    | '/api/admin/purchases/$id/tickets/remove'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  VerificarRoute: typeof VerificarRoute
  ApiConfigRoute: typeof ApiConfigRoute
  RifaIdRoute: typeof RifaIdRoute
  ApiAdminConfigRoute: typeof ApiAdminConfigRoute
  ApiAdminDashboardRoute: typeof ApiAdminDashboardRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiHealthDbRoute: typeof ApiHealthDbRoute
  ApiPurchasesTopClientsRoute: typeof ApiPurchasesTopClientsRoute
  ApiRafflesIdRoute: typeof ApiRafflesIdRouteWithChildren
  ApiRafflesFirstActiveRoute: typeof ApiRafflesFirstActiveRoute
  ApiRafflesPublishedRoute: typeof ApiRafflesPublishedRoute
  ApiTicketsVerifyRoute: typeof ApiTicketsVerifyRoute
  ApiPurchasesIndexRoute: typeof ApiPurchasesIndexRoute
  ApiRafflesIndexRoute: typeof ApiRafflesIndexRoute
  ApiAdminPurchasesIdRoute: typeof ApiAdminPurchasesIdRouteWithChildren
  ApiAdminRafflesIdRoute: typeof ApiAdminRafflesIdRouteWithChildren
  ApiAdminPurchasesIndexRoute: typeof ApiAdminPurchasesIndexRoute
  ApiAdminRafflesIndexRoute: typeof ApiAdminRafflesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verificar': {
      id: '/verificar'
      path: '/verificar'
      fullPath: '/verificar'
      preLoaderRoute: typeof VerificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/rifa/$id': {
      id: '/rifa/$id'
      path: '/rifa/$id'
      fullPath: '/rifa/$id'
      preLoaderRoute: typeof RifaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rifas': {
      id: '/admin/rifas'
      path: '/rifas'
      fullPath: '/admin/rifas'
      preLoaderRoute: typeof AdminRifasRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/crear': {
      id: '/admin/crear'
      path: '/crear'
      fullPath: '/admin/crear'
      preLoaderRoute: typeof AdminCrearRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/boletos': {
      id: '/admin/boletos'
      path: '/boletos'
      fullPath: '/admin/boletos'
      preLoaderRoute: typeof AdminBoletosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/raffles/': {
      id: '/api/raffles/'
      path: '/api/raffles'
      fullPath: '/api/raffles/'
      preLoaderRoute: typeof ApiRafflesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/purchases/': {
      id: '/api/purchases/'
      path: '/api/purchases'
      fullPath: '/api/purchases/'
      preLoaderRoute: typeof ApiPurchasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tickets/verify': {
      id: '/api/tickets/verify'
      path: '/api/tickets/verify'
      fullPath: '/api/tickets/verify'
      preLoaderRoute: typeof ApiTicketsVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/raffles/published': {
      id: '/api/raffles/published'
      path: '/api/raffles/published'
      fullPath: '/api/raffles/published'
      preLoaderRoute: typeof ApiRafflesPublishedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/raffles/first-active': {
      id: '/api/raffles/first-active'
      path: '/api/raffles/first-active'
      fullPath: '/api/raffles/first-active'
      preLoaderRoute: typeof ApiRafflesFirstActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/raffles/$id': {
      id: '/api/raffles/$id'
      path: '/api/raffles/$id'
      fullPath: '/api/raffles/$id'
      preLoaderRoute: typeof ApiRafflesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/purchases/top-clients': {
      id: '/api/purchases/top-clients'
      path: '/api/purchases/top-clients'
      fullPath: '/api/purchases/top-clients'
      preLoaderRoute: typeof ApiPurchasesTopClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/db': {
      id: '/api/health/db'
      path: '/api/health/db'
      fullPath: '/api/health/db'
      preLoaderRoute: typeof ApiHealthDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/dashboard': {
      id: '/api/admin/dashboard'
      path: '/api/admin/dashboard'
      fullPath: '/api/admin/dashboard'
      preLoaderRoute: typeof ApiAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/config': {
      id: '/api/admin/config'
      path: '/api/admin/config'
      fullPath: '/api/admin/config'
      preLoaderRoute: typeof ApiAdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/raffles/': {
      id: '/api/admin/raffles/'
      path: '/api/admin/raffles'
      fullPath: '/api/admin/raffles/'
      preLoaderRoute: typeof ApiAdminRafflesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/purchases/': {
      id: '/api/admin/purchases/'
      path: '/api/admin/purchases'
      fullPath: '/api/admin/purchases/'
      preLoaderRoute: typeof ApiAdminPurchasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/raffles/$id/pause-info': {
      id: '/api/raffles/$id/pause-info'
      path: '/pause-info'
      fullPath: '/api/raffles/$id/pause-info'
      preLoaderRoute: typeof ApiRafflesIdPauseInfoRouteImport
      parentRoute: typeof ApiRafflesIdRoute
    }
    '/api/admin/raffles/$id': {
      id: '/api/admin/raffles/$id'
      path: '/api/admin/raffles/$id'
      fullPath: '/api/admin/raffles/$id'
      preLoaderRoute: typeof ApiAdminRafflesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/purchases/$id': {
      id: '/api/admin/purchases/$id'
      path: '/api/admin/purchases/$id'
      fullPath: '/api/admin/purchases/$id'
      preLoaderRoute: typeof ApiAdminPurchasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/raffles/$id/unpause': {
      id: '/api/admin/raffles/$id/unpause'
      path: '/unpause'
      fullPath: '/api/admin/raffles/$id/unpause'
      preLoaderRoute: typeof ApiAdminRafflesIdUnpauseRouteImport
      parentRoute: typeof ApiAdminRafflesIdRoute
    }
    '/api/admin/raffles/$id/publish': {
      id: '/api/admin/raffles/$id/publish'
      path: '/publish'
      fullPath: '/api/admin/raffles/$id/publish'
      preLoaderRoute: typeof ApiAdminRafflesIdPublishRouteImport
      parentRoute: typeof ApiAdminRafflesIdRoute
    }
    '/api/admin/raffles/$id/pause': {
      id: '/api/admin/raffles/$id/pause'
      path: '/pause'
      fullPath: '/api/admin/raffles/$id/pause'
      preLoaderRoute: typeof ApiAdminRafflesIdPauseRouteImport
      parentRoute: typeof ApiAdminRafflesIdRoute
    }
    '/api/admin/raffles/$id/auto-pause': {
      id: '/api/admin/raffles/$id/auto-pause'
      path: '/auto-pause'
      fullPath: '/api/admin/raffles/$id/auto-pause'
      preLoaderRoute: typeof ApiAdminRafflesIdAutoPauseRouteImport
      parentRoute: typeof ApiAdminRafflesIdRoute
    }
    '/api/admin/purchases/$id/status': {
      id: '/api/admin/purchases/$id/status'
      path: '/status'
      fullPath: '/api/admin/purchases/$id/status'
      preLoaderRoute: typeof ApiAdminPurchasesIdStatusRouteImport
      parentRoute: typeof ApiAdminPurchasesIdRoute
    }
    '/api/admin/purchases/$id/tickets/remove': {
      id: '/api/admin/purchases/$id/tickets/remove'
      path: '/tickets/remove'
      fullPath: '/api/admin/purchases/$id/tickets/remove'
      preLoaderRoute: typeof ApiAdminPurchasesIdTicketsRemoveRouteImport
      parentRoute: typeof ApiAdminPurchasesIdRoute
    }
    '/api/admin/purchases/$id/tickets/reassign': {
      id: '/api/admin/purchases/$id/tickets/reassign'
      path: '/tickets/reassign'
      fullPath: '/api/admin/purchases/$id/tickets/reassign'
      preLoaderRoute: typeof ApiAdminPurchasesIdTicketsReassignRouteImport
      parentRoute: typeof ApiAdminPurchasesIdRoute
    }
    '/api/admin/purchases/$id/tickets/add': {
      id: '/api/admin/purchases/$id/tickets/add'
      path: '/tickets/add'
      fullPath: '/api/admin/purchases/$id/tickets/add'
      preLoaderRoute: typeof ApiAdminPurchasesIdTicketsAddRouteImport
      parentRoute: typeof ApiAdminPurchasesIdRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBoletosRoute: typeof AdminBoletosRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminCrearRoute: typeof AdminCrearRoute
  AdminEmailsRoute: typeof AdminEmailsRoute
  AdminRifasRoute: typeof AdminRifasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBoletosRoute: AdminBoletosRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminCrearRoute: AdminCrearRoute,
  AdminEmailsRoute: AdminEmailsRoute,
  AdminRifasRoute: AdminRifasRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ApiRafflesIdRouteChildren {
  ApiRafflesIdPauseInfoRoute: typeof ApiRafflesIdPauseInfoRoute
}

const ApiRafflesIdRouteChildren: ApiRafflesIdRouteChildren = {
  ApiRafflesIdPauseInfoRoute: ApiRafflesIdPauseInfoRoute,
}

const ApiRafflesIdRouteWithChildren = ApiRafflesIdRoute._addFileChildren(
  ApiRafflesIdRouteChildren,
)

interface ApiAdminPurchasesIdRouteChildren {
  ApiAdminPurchasesIdStatusRoute: typeof ApiAdminPurchasesIdStatusRoute
  ApiAdminPurchasesIdTicketsAddRoute: typeof ApiAdminPurchasesIdTicketsAddRoute
  ApiAdminPurchasesIdTicketsReassignRoute: typeof ApiAdminPurchasesIdTicketsReassignRoute
  ApiAdminPurchasesIdTicketsRemoveRoute: typeof ApiAdminPurchasesIdTicketsRemoveRoute
}

const ApiAdminPurchasesIdRouteChildren: ApiAdminPurchasesIdRouteChildren = {
  ApiAdminPurchasesIdStatusRoute: ApiAdminPurchasesIdStatusRoute,
  ApiAdminPurchasesIdTicketsAddRoute: ApiAdminPurchasesIdTicketsAddRoute,
  ApiAdminPurchasesIdTicketsReassignRoute:
    ApiAdminPurchasesIdTicketsReassignRoute,
  ApiAdminPurchasesIdTicketsRemoveRoute: ApiAdminPurchasesIdTicketsRemoveRoute,
}

const ApiAdminPurchasesIdRouteWithChildren =
  ApiAdminPurchasesIdRoute._addFileChildren(ApiAdminPurchasesIdRouteChildren)

interface ApiAdminRafflesIdRouteChildren {
  ApiAdminRafflesIdAutoPauseRoute: typeof ApiAdminRafflesIdAutoPauseRoute
  ApiAdminRafflesIdPauseRoute: typeof ApiAdminRafflesIdPauseRoute
  ApiAdminRafflesIdPublishRoute: typeof ApiAdminRafflesIdPublishRoute
  ApiAdminRafflesIdUnpauseRoute: typeof ApiAdminRafflesIdUnpauseRoute
}

const ApiAdminRafflesIdRouteChildren: ApiAdminRafflesIdRouteChildren = {
  ApiAdminRafflesIdAutoPauseRoute: ApiAdminRafflesIdAutoPauseRoute,
  ApiAdminRafflesIdPauseRoute: ApiAdminRafflesIdPauseRoute,
  ApiAdminRafflesIdPublishRoute: ApiAdminRafflesIdPublishRoute,
  ApiAdminRafflesIdUnpauseRoute: ApiAdminRafflesIdUnpauseRoute,
}

const ApiAdminRafflesIdRouteWithChildren =
  ApiAdminRafflesIdRoute._addFileChildren(ApiAdminRafflesIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  VerificarRoute: VerificarRoute,
  ApiConfigRoute: ApiConfigRoute,
  RifaIdRoute: RifaIdRoute,
  ApiAdminConfigRoute: ApiAdminConfigRoute,
  ApiAdminDashboardRoute: ApiAdminDashboardRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiHealthDbRoute: ApiHealthDbRoute,
  ApiPurchasesTopClientsRoute: ApiPurchasesTopClientsRoute,
  ApiRafflesIdRoute: ApiRafflesIdRouteWithChildren,
  ApiRafflesFirstActiveRoute: ApiRafflesFirstActiveRoute,
  ApiRafflesPublishedRoute: ApiRafflesPublishedRoute,
  ApiTicketsVerifyRoute: ApiTicketsVerifyRoute,
  ApiPurchasesIndexRoute: ApiPurchasesIndexRoute,
  ApiRafflesIndexRoute: ApiRafflesIndexRoute,
  ApiAdminPurchasesIdRoute: ApiAdminPurchasesIdRouteWithChildren,
  ApiAdminRafflesIdRoute: ApiAdminRafflesIdRouteWithChildren,
  ApiAdminPurchasesIndexRoute: ApiAdminPurchasesIndexRoute,
  ApiAdminRafflesIndexRoute: ApiAdminRafflesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
